### ISSUE TITLE
[REQ] Support for currency name conjugation

### ISSUE THREAD

**Issue by ShadowDrakken** [iConomy/Core#1]
As of iConomy 4.1, iConomy uses a single tag for currency name regardless of how much money a player has. Using a plural is fine for 0-0.99 and for 1.01+, or using a singular name is fine for exactly 1.00.

I recommend adding a new [optional] config param Currency_Single: that if used, will use be displayed for 1.00 (and -1.00) and then use Currency: for everything else. If not set, then Currency: will be used for both.

This is just to add a level of professionalism to the user display.

**Comment by nijikokun** [comment]
On the TODO.

**Comment by nijikokun** [comment]
Added in 4.6+
