### ISSUE TITLE
Dungeons and raids for iconomy!

### ISSUE THREAD

**Issue by AvolovaCraft** [iConomy/Core#104]
I don't know where i got this idea from...world of warcraft perhaps xd
But anyway...
My idea is to take iconomy to a whole new level by adding raids, instances, dungeon or what ever you wanna call it in to iconomy and in to minecraft!
It works by an admin using an npc edit side program or an program ingame that will alow him to create and edit his own monsters.
The admin will then have the availability to edit size, color, lvls of monsters(higher lvls for boss),parts for monster, name, special attacks except hitting, editing weapons for monsters and more!
There will also be loot, where the admin will decide what it will drop, how it will drop items (for example, a chest with loot, or it drops all at death...also thought about the monsters to drop items under the battle like food).
Then there would be level systems so if a person/persons have completed a dungeon (wich will be last boss) , that person will get a level and will be able to go for harder instances...
Instances will hold groups of monsters as side mobs except the bosses.
A player will have the availablility to join groups for dungeons in the chat!
There can be instances from 1 person to 100 persons, what ever the admin descide the instance to be!
If he then chooses to have a 100 people instance, it will get automaticly alot harder for the players to complete it!
By levels i mean that they have more hp and hit harder etc...
Dungeons will then be reachable by portal, or a person that summons others to join and the summoned player automaticly teleports to the dungeon.
To edit the dungeons you can choose any program or just go for old classic minecraft pickaxe building...but first you will have to enter a size for the dungeon and then you can only build inside the sized area wich is all up to you how big it will be ofc...
This will ofc take alot of computer power and it would be quite hard to program...
But i think that the idea is good generaly and i hope it will be possible, if not today...then some day in the near future!

Thanks for reading!
Cheers :)

**Comment by nijikokun** [comment]
Nice! make it a plugin!
