### ISSUE TITLE
I'm So Lost. Can someone please help me?(I'm a noob)

### ISSUE THREAD

**Issue by TurtleThatCould** [iConomy/Core#109]
So I tried to follow the directions and I'm am just flat-out confused. It all starts with Permissions. I download it and do the stuff, but I'm not sure what I need or don't need to change in the rename-me.yml. But lets say I have that all setup, and I want to put iConomy on my Server, I have no clue where to place it other then the plugin folder and I have not found that at all. But then I have no clue how to actually set iConomy up. I'm not sure where to put anything or how I'm suppose to make it work. My attempt ended up not making all the files all folders iConomy should. I'm lost on what to do. PLEASE help. Thanks!

**Comment by nijikokun** [comment]
you just put the jar in the plugins folders and start the server, the jar file will make the files.

**Comment by TurtleThatCould** [comment]
So I put the iConomy.jar in my plugins folder and start the server and everything else should happen by itself?

**Comment by TurtleThatCould** [comment]
And I'm still unsure of where the plugins folder is. I have checked through my .minecraft and my minecraft server folder several times but I can't find it. Should I just make one? and if i should where should i put it?

**Comment by nijikokun** [comment]
This is for bukkit, not vanilla MP, or SP
