### ISSUE TITLE
an internal error occurred while attempting to perform this command.

### ISSUE THREAD

**Issue by mjongerh** [iConomy/Core#118]
[b]Craftbukkit Version:[/b] b953
[b]iConomy version:[/b] 5.0.1

[b]Current Issue / Error:[/b]
when i use commands from some 3th party plugings like simpleshop. i get: an internal error occurred while attempting to perform this command.

[b]Console Output w/ Full Error[/b](Preferably using http://pastie.org or http://pastebin.com):
http://pastie.org/2166675

[i]What you were doing?[/i]
i was adding an item to the shop with /shop add 1:64 10 5
(plugin: http://bit.ly/iQUgWj )

[i]Were you upgrading?[/i]
no

[i]Is this a reoccuring issue?[/i]
yes, also with different plugins.

**Comment by TONiOG** [comment]
hey mjongerh I have the same problem :/ did you resolve it in any way? thanks

**Comment by mjongerh** [comment]
yeah i got the solution.
simpeshop is not protable with the new 5.0.1 version of iconomy.
i just installed 4.6 and all is working fine.
