### ISSUE TITLE
I can't make iConomy work

### ISSUE THREAD

**Issue by MoeTM** [iConomy/Core#127]
Hi, please can you help with this problem that I have?
The error is:
[info] [iConomy] Could not create connection: org.h2.jdbcSQLException: File corrupted while reading record: "-1 of 532". Possible solution: use the recovery tool; SQL statement:
CREATE CHACHED TABLE IF NOT EXISTS INFORMATION_SCHEMA.LOB_MAP(
    LOB BIGINT NOT NULL'
    SEQ INT NOT NULL,
    HASH INT,
    BLOCK BIGINT

> [INFO] [iConomy] Database initialization failed: java.lang.NullPointerException
> [info] [iConomy] Plugin disabled.

all I have done is C&P the .jar  file into the plugins foder turned the server on and then it gave me this error, the only other thing that I have done is change the money to pounds and pence. When I first saw the error I decided to change the database type from H2SQL to H2. How would I fix this? and I tryed to read th FQA but didn't understand it and I didn't get 1 bit from the insallation place too, so if you could make it easyer for the more dim people in this world it would help allot for most people. Thanks for takeing the time to read this. Also here is a folder of :
1. A picture of the CMD file with the error.
2. the error again.
3. and finaly the iConamy folder in my plugins folder.
http://dl.dropbox.com/u/33487921/Help%20from%20MoeTM.zip

Hope fully this will help.
-MoeTM

**Comment by mobilehobo** [comment]
I have been having the same issue, except it started out of random one day and has been ongoing whenever I restart the server.
