### ISSUE TITLE
Selectable Iconomy

### ISSUE THREAD

**Issue by selonianth** [iConomy/Core#134]
I run multiple worlds on my server with Multiverse. I want one of my worlds to have Towny and iConomy but unfortunately atm that is not possible because adding iconomy would give me it on every world which is not desirable on a freebuild world. I'm suggesting this function get added please.

**Comment by thdxr** [comment]
Do not give users permissions to access /money commands on other worlds.

**Comment by nijikokun** [comment]
What SwearWord said.
