### ISSUE TITLE
/money pay suddenly doesn't work.

### ISSUE THREAD

**Issue by dagumboss** [iConomy/Core#136]
Craftbukkit Version: b1000
 iConomy version: 5.0.1 
Current Issue / Error: I updated to Permissions 3 earlier this weekend. I didn't receive any error reports from players. Then I installed the Jobs plugin. Didn't notice any errors. I came back later and apparently /money pay doesn't work anymore. I disabled Jobs and it still doesn't work. It works for ops and all, so I assume it's permissions, but I'm not seeing any issues with the permissons. 
Console Output w/ Full Error: I don't get any errors in the console 
What you were doing? Installing Permissions and Jobs 
Were you upgrading? Permissions 
Is this a reoccuring issue? Recurring in the sense that they still can't use it, yes, but this has never happened before.

**Comment by Soorena** [comment]
I had the same issue so I deleted both, then installed iConomy 6 for now...but the perm nodes for iConomy 6 don't work for me. (Using Permissions 3.1.6
