### ISSUE TITLE
Admin of server can use this plugin but normal player can't use it.

### ISSUE THREAD

**Issue by kritnopap** [iConomy/Core#141]
Admin of server can use this plugin but normal player can't use it.

**Comment by DasKrieger** [comment]
@kritnopap: You should learn how to make a proper Bug Report.

@Nijikokun: I hope this helps get the issue solved.

Craftbukkit Version: b1060
iConomy version: 6

Current Issue / Error: Only Op is able to use /money and anything related to it, chat response: Invalid Command Usage: You do not have permission to do that.

Console Output w/ Full Error: Console isn't showing anything

What you were doing?: Tried to get iConomy 6 working with PermissionsBukkit

Were you upgrading?: No, Started with a clean Server

Is this a reoccuring issue?: Yes
