### ISSUE TITLE
H2.db to sql

### ISSUE THREAD

**Issue by jonathanwgnz** [iConomy/Core#146]
hi, Ive followed how to convert the h2.db to sql from here http://ico.nexua.org/Main/FAQ#toc28 
It only made a 1kb sql file with no information about peoples accounts. Any one knows how to do this?

Thanks
Jonathan

**Comment by jonathanwgnz** [comment]
btw im using iconomy 5 atm

**Comment by nijikokun** [comment]
Convert to 6.0.3b and use MySQL as your database.
