### ISSUE TITLE
Getting money from killing mobs

### ISSUE THREAD

**Issue by SissyZ** [iConomy/Core#147]
I can not figure out how to do when you kill mobs to get money. Help please

**Comment by thdxr** [comment]
You need to get a separate plugin. This is not the place to post this.

**Comment by SissyZ** [comment]
What is the plugins name?

**Comment by SissyZ** [comment]
What is the plugins name?

 -------- Оригинално писмо --------

От: SwearWord reply@reply.github.com

Относно: Re: [Core] Getting money from killing mobs (#147)

До: sissyz@abv.bg

Изпратено на: Събота, 2011, Август 27 23:45:54 EEST

You need to get a separate plugin. This is not the place to post this.

## 

Reply to this email directly or view it on GitHub:

 https://github.com/iConomy/Core/issues/147#issuecomment-1921390 

<BR/><BR/>-----------------------------------------------------------------<BR/>
<a href="http://a.abv.bg/www/delivery/ck.php?oaparams=2__bannerid=6818__zoneid=63__oadest=http://bg.tempobet.com/affiliates/3208311" target="_blank"> 100 лв БОНУС. Най-високи коефициенти. Tempobet.com </a>
