### ISSUE TITLE
[REQ] add them to the mysql table after they actually get money

### ISSUE THREAD

**Issue by SlipMage** [iConomy/Core#15]
I was just wondering if it was possible to add them to the table after they actually get money if they arent already on the mysql table because we run a whitelisted server and they are getting added even when they cant get on the server. I made a post in the bukkit forums about this but im about to fix that and figured I'd put it here. 

Adding people on connect that cant even get on the server in the first place is a big resource waste for people that dont have much space and are limiited on how mush database space they can use.

**Comment by nijikokun** [comment]
It adds whenever someone joins not logs in which is when the whitelist should kick them and they would never had joined however, the whitelist is weird and kicks them when they join not login, that would be a issue you would have to talk to with the plugin maker, or someone who made whatever whitelist system you are using.

**Comment by SlipMage** [comment]
the default one lol, but thanks for the response on that, seems bukkit still has a long ways to go hehe :)
