### ISSUE TITLE
5.01 to 6.0.x Conversion

### ISSUE THREAD

**Issue by lelouch48625** [iConomy/Core#154]
Error I get 
03.03 10:44:44 [Server] INFO java.sql.SQLException: No suitable driver found for h2:path/to/iConomy/folder/iConomy;AUTO_RECONNECT=TRUE

I have tried all possible paths including ('mysql://localhost:3306/iConomy')

Heres the 5.01 Config
    Database:
        Type: 'H2SQL'                                 # H2 or MySQL
        Settings:
          Name: 'minecraft'
          Table: 'iConomy'
          MySQL:
              Username: 'root'
              Password: 'pass'
              Hostname: 'localhost'
              Port: 3306

Heres 6.0.9b Config
      Enabled: true

```
  # Database Type, H2DB or MySQL
  Type: 'H2DB'

  # Database Table
  Table: 'iConomy'

  # Database URL without table at the end.
  URL: 'h2:path/to/iConomy/folder/iConomy;AUTO_RECONNECT=TRUE'

  # Username / Password
  # H2DB does not use this. MySQL Only.
  Username: 'root'
  Password: 'pass'

  # Unused ATM.
  All: true
```

**Comment by richboos** [comment]
Had similar problem just 20 minutes ago even though I use MySQL.  The default database in iCon6 is "iConomy" but in 5 it was "minecraft".  It is possible you can fix it by changing the "URL:" line to this:
  URL: 'h2:path/to/iConomy/folder/minecraft;AUTO_RECONNECT=TRUE'
or any other setting for the conversion where you can change "iConomy" to "Minecraft"
Keep the Table: 'iConomy' the same, because the table was called that in both versions.  It is the database name that changed between versions.

**Comment by Sanzennin** [comment]
So, what exactly am I supposed to write for the URL? Lets say its on a professional host, so, its h2://localhost:3306, right? After that, what? plugins/iconomy;AUTO_RECONNECT=TRUE? /minecraft/plugins/iconomy;AUTO_RECONNECT=TRUE? /plugins/iconomy/iconomy;AUTO_RECONNECT=TRUE? /plugins/iconomy/minecraft;AUTO_RECONNECT=TRUE

I got the database named: minecraft.h2.db, and its located at plugins/iconomy
But no matter what I type, I always get: 
java.sql.SQLException: No suitable driver found for h2://localhost:3306/iConomy/minecraft
java.sql.SQLException: No suitable driver found for h2://localhost:3306/iConomy/iConomy
java.sql.SQLException: No suitable driver found for h2://localhost:3306/plugins/iConomy/minecraft
java.sql.SQLException: No suitable driver found for h2://localhost:3306/plugins/iConomy/iConomy

Any help?

**Comment by richboos** [comment]
Sorry that was the extent of my knowledge.  Never used anything but MySQL

**Comment by Sanzennin** [comment]
Oh dang.

Well, thanks anyways, hope the author notices and replies here too.

**Comment by richboos** [comment]
FYI went back to iCon5 with an updated jar http://www.palmergames.com/downloads/
