### ISSUE TITLE
Interest not Broadcasting

### ISSUE THREAD

**Issue by richboos** [iConomy/Core#155]
With iConomy6 + PEX/bpermissions (either) and HeroChat the interest is not being broadcast to any players.  

I downgraded to iConomy5 just to fix this, but it broke with craftbukkit for 1.2

**Comment by MariuszT** [comment]
Yep, same situation here. iConomy 6.0.9b, bukkit 2050, PEX.

**Comment by richboos** [comment]
FYI went here to go back to icon5 which is updated http://www.palmergames.com/downloads/
