### ISSUE TITLE
/money top - Console spam and latency

### ISSUE THREAD

**Issue by richboos** [iConomy/Core#156]
With the most recent iConomy RB the new (and very welcomed!!) command /money top takes about 3-4 seconds to work, even though I only have under 30 users in the database.  It is probably related to this console error:

18:10:45 [INFO] [iConomy] Error issueing SQL query: java.sql.SQLException: Unknown column 'status' in 'field list' Query: SELECT status FROM iConomy WHERE username=? Parameters: [inthepastxx]

There are 5 of these, one for each of the top 5 wealthiest players.

**Comment by graywolf336** [comment]
I'm also getting this when I type /money top, except it kicks me off the server and causes the whole server to lag for about 5-10 seconds. Then this error log showed in the console:

http://pastebin.com/1W8rrBG6

It seems that whenever I do /money top 5 it actually does show the top five but it doesn't display their amount and it spams the console.
http://pastebin.com/s0Q7uF0V

**Comment by drnod** [comment]
Same here, Server freeze in this time.

**Comment by spathizilla** [comment]
Looks like iCo6 is trying to pull everyone's records individually and then iterate over them. Why not just order using the sql query?

**Comment by ghost** [comment]
Server froze at our end, the plugin made 12k+ queries (One for each account on file) on our MySQL database.

**Comment by Enf0** [comment]
Having the same problem here. Server kicks you out and freezes for 10-30 seconds whenever you do /money top

**Comment by richboos** [comment]
FYI I "upgraded" to iConomy5 with a jar compatible with Bukkit in the MC1.2.3 era
http://www.palmergames.com/downloads/

**Comment by spoothie** [comment]
Any chance this will be fixed?
