### ISSUE TITLE
Can not create account for new players

### ISSUE THREAD

**Issue by richboos** [iConomy/Core#157]
13:37:12 [INFO] [iConomy] Error issueing SQL query: java.sql.SQLException: Unknown column 'status' in 'field list' Query: INSERT INTO iConomy(username, balance, status) values (?, ?, ?) Parameters: [inumedia, 30.0, 0]

Should be noted that this database was upgraded from iConomy5 to iConomy6 using the built-in upgrade method.  
This error happens the first time a new player joins.

**Comment by Grimmy347** [comment]
I am also having this exact issue with same situation.

**Comment by nijikokun** [comment]
o.o I see why it's not updating and will fix this.

**Comment by Grimmy347** [comment]
please fix soon, log file fills up fast when everything a new player does throws an error and none of their money is saved  =/

**Comment by stephenthoma** [comment]
Is this fixed? I'm still getting this error

**Comment by nijikokun** [comment]
It's an SQL update that you need; I don't know why it never patched it.

On your SQL Server run this:

`ALTER TABLE iConomy ADD status int(2) NOT NULL DEFAULT '0'`

**Comment by stephenthoma** [comment]
My iConomy table has that column, but the errors persist. Using iConomy 5.0.1 if that makes any difference.

Also, sorry I should have mentioned. My problem has the same symptom, but the error is different. It is "[INFO] [iConomy] Error grabbing / creating account for: player"
