### ISSUE TITLE
Will you Develop an Iconomy for mionecraft 1.2.3?

### ISSUE THREAD

**Issue by Muzako** [iConomy/Core#158]
I Been Wondering if you are going to upgrade the plugin for mincraft 1.2.3?

**Comment by Muzako** [comment]
I Know its not an issue but i needed to ask you

**Comment by lucasdidur** [comment]
Please Update

**Comment by graywolf336** [comment]
It should work when he released the one for 1.1-r7 at http://dev.bukkit.org/server-mods/iconomy/files/7-6-0-9b/

**Comment by Muzako** [comment]
I'll Try It.

**Comment by Muzako** [comment]
Thanks, It Works
