### ISSUE TITLE
NPE On Startup

### ISSUE THREAD

**Issue by SERVERCONSOLE** [iConomy/Core#162]
Exception in thread "Thread-13" 
08:54:54 [SEVERE] java.lang.NullPointerException
08:54:54 [SEVERE]   at com.iCo6.IO.mini.Arguments.decode(Arguments.java:38)
08:54:54 [SEVERE]   at com.iCo6.IO.mini.Arguments.getValue(Arguments.java:50)
08:54:54 [SEVERE]   at com.iCo6.IO.mini.Arguments.getDouble(Arguments.java:58)
08:54:54 [SEVERE]   at com.iCo6.system.Queried.purgeDatabase(Queried.java:529)
08:54:54 [SEVERE]   at com.iCo6.iConomy$2.run(iConomy.java:264)
08:54:54 [SEVERE]   at com.iCo6.util.Thrun.run(Thrun.java:12)

**Comment by czerni** [comment]
Same Error
Using 
iConomy v7.0,
Vault v1.2.14-b164
Jobs v2.7.4
