### ISSUE TITLE
Admin Shop Problem

### ISSUE THREAD

**Issue by Macapple96** [iConomy/Core#163]
Hi everyone,i got a problem with the Admin Shop creation...

Step 1: I place a sign on a wall

Step 2: I edit sign like this:

Admin Shop
        64
    100:50
     Arrow

A console message says : [Shop] Shop created!
But when a player tries to buy (with right mouse button) it does anything...no messages,no arrows in inventory...
Selling also doesn't work
I installed Chest Shop and iConomy6
Help me,how can i fix this?

:)

**Comment by jaboy** [comment]
it does NOThing (not anything)

and it sounds like a problem with the other pulgin ... like you forgot to give your self permission
