### ISSUE TITLE
template reseting after reload and after a restart

### ISSUE THREAD

**Issue by ghost** [iConomy/Core#166]
So i have the problem that my template.yml is resetting. When i edit the template.yml the server is shutdowned. When i was finish i loaded it up. After it was loaded up i started the server, but the template.yml is resetting itself..
Yes file perms and so are setted right!(im on debian maybe this helps)

**Comment by nijikokun** [comment]
I will look into this.

**Comment by ghost** [comment]
ok thx because now i cant translate iconomy into german :-( that is bad for a german server..
