### ISSUE TITLE
/money status KJanar set problem

### ISSUE THREAD

**Issue by ghost** [iConomy/Core#168]
Can you please tell me what is the point of that command? Because I can't really think of any use for it.

Maybe if it would support a letter value not number only then I could set like a comment on a account "Stolen" or "Hacked Money" but it only takes number values.

I tried "/money status KJanar set 5" and that set my accounts status to 5. Why do I need a status?

I then tried "/money status set Active" and I got ann internal error. First thought was I can set like comments on accounts, but no.

So please give a short explanation why there is such a command and what it does. Thank you!

**Comment by nijikokun** [comment]
this is for on/off for top account listings.
