### ISSUE TITLE
IMPORTANT: Users money resetting for unknown reasons.

### ISSUE THREAD

**Issue by novs12** [iConomy/Core#171]
Since the 1.2.4 update all users money is being reset at non-specific times.
I'm using the default money storage system, not a database.

It reset users money more than once now for no reason, i did not restart the server or anything.
On latest bleeding edge build.
Latest craftbukkit dev build.

**Comment by nijikokun** [comment]
There is a plugin causing this issue.

**Comment by tjfoxhound** [comment]
What plugin is causing the issue?
