### ISSUE TITLE
Players Randomly getting money

### ISSUE THREAD

**Issue by MoNeYBaGSMC** [iConomy/Core#172]
I have disabled interest, and there is no way for their money to be increasing like it is. I type in /money top and there are people with 3 mil and 5 mil when they had 500,000 2 seconds ago. The money keeps adding up as time goes on..

**Comment by nijikokun** [comment]
Do you have interest on?

**Comment by CubieX** [comment]
Same error here. iConomy 6.0.9b on MC 1.2.4.
Interest is set to 50 Dollars 604800 seconds, (see my config here: http://forums.bukkit.org/threads/econ-iconomy-6-0-7-celty-1337.40/page-169#post-1056321) but today our players got about 100 dollars every 2 minutes.
We deactivated interests atm....
