### ISSUE TITLE
Severe lag/server lock-up with rapid transactions and MySQL backend

### ISSUE THREAD

**Issue by WoodenAxe** [iConomy/Core#178]
related: http://www.assembla.com/spaces/iConomy/tickets/212

Using ChestShop and with quick buy/sell (even with a rate limit of 1 per second set in the ChestShop config) the server is being lagged into submission. Same effect with 1 player on or 50.

**Comment by SeanStar** [comment]
Same thing happening to me.. I can confirm this is an issue with the MySQL backend, even with the MySQL server being hosted locally.

**Comment by ChrisLane** [comment]
This needs fixing fast. I don't know if there's a way to transfer all my mysql datatables into a local db.

**Comment by Psithief** [comment]
Change the MySQL database storage engine to InnoDB. InnoDB has row-level locking instead of table-level locking, and thus withstands constant updates much better.

`ALTER TABLE iconomy ENGINE = InnoDB`; where iconomy is the database table's name.

It will still cause lag but only slightly.

**Comment by WoodenAxe** [comment]
It already was InnoDB

**Comment by Psithief** [comment]
@WoodenAxe 

Then you're screwed. Sorry.

**Comment by ChrisLane** [comment]
I'm now using minidb and it works just fine.

**Comment by linkinkov** [comment]
need fix it. have same problem.

**Comment by me4502** [comment]
This issue still occurs, it needs to be fixed.

**Comment by Puremin0rez** [comment]
Since i'm assuming this plugin is dead and i'm still getting this issue, does anyone know if this issue only pertains to iConomy? I've been thinking of switching to Fe Economy.
