### ISSUE TITLE
New User has no account

### ISSUE THREAD

**Issue by jascotty2** [iConomy/Core#18]
using 4.4.4, from 4.4.3, new users are no longer created in the database
using MySQL and Cache: false

**Comment by nijikokun** [comment]
Need console / logs, usually means a connection issue.

**Comment by jascotty2** [comment]
not a connection issue, since player got money later buy killing monsters
there was no error message when the player logged in, either
to make it more confusing: i tried with another player & it worked fine.
(just thought i'd post here, just to let you know that it happened)
