### ISSUE TITLE
Server crash caused by money status and money top

### ISSUE THREAD

**Issue by ghost** [iConomy/Core#181]
There's an issue that causes a enitre servercrash.
When you set with /money status an account to 1 and then use /money top
There are no error in the log.

Tested on a clean Bukkitserver on 1.2.5 RB1.0 (Build#2143) with iConomy v6.0.10b only (no other plugins installed).

**Comment by nijikokun** [comment]
just straight up crashes?

**Comment by ghost** [comment]
Yes, first all entities freeze and then read time out.

**Comment by vvswarhead** [comment]
+1 same problem

**Comment by nijikokun** [comment]
What database system?

**Comment by vvswarhead** [comment]
I use 5.1

**Comment by ghost** [comment]
I tested it with MiniDB/Flatfile and MySQL. Same results.

**Comment by linkinkov** [comment]
with MiniDB/Flatfile normal. Mysql have this problem.
