### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by kulter20** [iConomy/Core#189]
So I've seen some posts of this one but couldn't find a answer. 

In advance, I've read the FAQ's and other stuff but still I haven't managed to get this working.

The problem is, me as op, is able to do everything with the /money. 

Now I can send money with /money pay <name> <amount> but my other players can't. I've seen that the groups are now changed to the persons themselves but I tried to change the .holdings but nothing worked. I see default is set as op but as I change it nothing will happen.

There is no clear guidance to do this nor any video or information. I want to have some tradings in my server but without the /money pay players can't pay for their items. I would appreciate it if you could take some time and tell me what I do wrong because I probably do something wrong. 

Thanks in advance,

Kulter20´

EDIT:

A friend helped me with this, but it's probably a bug that the plugin doesn't make any pay/help permissions to the normal user. Only to ops/admins. We used ! Groupmanager and essentials ! for this and edited the permission groups or in fact added the permissions of iConomy into the permissions of essentials. 

Maybe a good tip to create a guidance or turn this in the installation for the people who have trouble with this.

**Comment by jaboy** [comment]
http://dev.bukkit.org/server-mods/iconomy/pages/faq/
