### ISSUE TITLE
Balance Reset Bug

### ISSUE THREAD

**Issue by Fureniku** [iConomy/Core#190]
So after browsing tickets this bug still hasn't been solved so to speak, there was one ticket (which I commented on) that is now closed as the OP has moved to another plugin - frankly I don't blame him right now.

Another ticket the dev just said "its caused by another plugin". OK? What plugin? Where is your proof? How did you get that conclusion?

I've used iConomy since hMod - even found a v1 copy when cleaning my computer the other day and I really don't want to switch... but I'm running out of options here. I'm losing users because of this bug... It has a knock on effect you know. The bug wipes money -> towns cant afford upkeep so crumble -> hours of work reclaiming towns, open to grief the land and sometimes destroying the town itself. Its a serious bug...

**Comment by SeanStar** [comment]
I've been having the same exact issue, it only happens when using the flatfile though...
Can't use the MySQL backend either because it doesn't handle rapid transactions without massively lagging the entire server, so I'm at a loss here.

**Comment by Fureniku** [comment]
Just pulled this little error from console if its any help. Not like you're replying anyway but yeah guess we can hope.

10:49:17 [INFO] Read timed out
10:56:45 [SEVERE] java.io.FileNotFoundException: plugins/iConomy/accounts.mini (Too many open files)
10:56:45 [SEVERE] [Metrics] Too many open files
10:56:45 [INFO] java.io.FileNotFoundException: plugins/iConomy/accounts.mini (Too many open files)
10:56:45 [SEVERE] java.io.FileNotFoundException: plugins/iConomy/accounts.mini (Too many open files)
10:56:45 [SEVERE] java.io.FileNotFoundException: plugins/iConomy/accounts.mini (Too many open files)
10:56:45 [INFO] java.io.FileNotFoundException: plugins/iConomy/accounts.mini (Too many open files)
10:56:45 [SEVERE] java.io.FileNotFoundException: plugins/iConomy/accounts.mini (Too many open files)

**Comment by tappestry** [comment]
having same problems. flatfile wiped completely. this is twice in less than 2 weeks now.

**Comment by animalvgamer** [comment]
I have the same problem, and this seems to happen almost every day now, it definitely is a flatfile issue. Can we bring back H2 databases?

**Comment by Mastergalen** [comment]
Yep, same issue.

Switched to a MySQL database.

**Comment by Fureniku** [comment]
Then you get the issue of rapid transactions crashing the server. We use ChestShop - if people wanna buy 2 stacks of torches and someone sells them individually they tend to spam-click the sign and that'd hang or crash...

Judging by the dev's lack of reply, and the fact the code hasn't been updated at all in nearly a month, I'm starting to question how much longer iConomy will last. I've decided that next time my econ crashes, I'm moving to BOSeconomy unless he's at least given an indication he actually cares.

It'd be a shame, I've always liked his work... but I don't wanna have to restock money into all my towns every few days.

**Comment by Psithief** [comment]
@Flenix
Change the MySQL database storage engine to InnoDB. InnoDB has row-level locking instead of table-level locking, and thus withstands constant updates much better.

`ALTER TABLE iconomy ENGINE = InnoDB;` where `iconomy` is the database table's name.

It will still cause lag but only slightly.

**Comment by nijikokun** [comment]
@Psithief I may change this in the next release.
