### ISSUE TITLE
[Suggestion] Reset balance after you died

### ISSUE THREAD

**Issue by Mike2033** [iConomy/Core#192]
Hello,

what about a option which allows you to reset balance when you die. That would make it more realistic and it's not duty because you can configure this option in the YML file.

Thanks

**Comment by Fureniku** [comment]
I think there are plugins which charge you for dying. Have a look I'm sure at least one would just take as much as possible if you can't afford it all - set it to take 10 billlion and you'll be sorted :P

**Comment by Mike2033** [comment]
Sorry for late response lol. Didn't found the messenger in GitHub :D Thanks for your tip
