### ISSUE TITLE
Money Top Delay

### ISSUE THREAD

**Issue by mmenanno** [iConomy/Core#200]
Using /money top the "wealthiest accounts" appears right away but the actually account listings take about 30 seconds to actually appear and lag the server while it attempts to get this info.

Also one of my members crashed the server buy spamming the command /money top 10 which upon a single use produces this error:

02.05 20:09:33 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:33 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:33 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:33 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:33 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:33 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:33 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:33 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:33 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
02.05 20:09:32 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
02.05 20:09:32 [Server] INFO [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

**Comment by ImDeity** [comment]
We're also having this issue. It never shows the list and just spits out those "Communications link failture" messages after a while.

We have a  50,000+ accounts in our iConomy table which may be the reason why its timing out. I've had to disable the money top command.

**Comment by mmenanno** [comment]
mySQL is designed to handle billions of connections at once though so this shouldn't be happening and it's annoying :/

**Comment by netherfoam** [comment]
It's because the plugin doesn't cache accounts (Properly, why aren't offline players cached??? Offline players get interacted with too!). my best guess is it's fetching from the database like
"Are you the richest?' Nope
'Are you the richest?' Nope
'Are you the richest?' Nope
....x50,000
Instead of 'Which one is the richest?' Me. 
(Or at worst, it could use the cache to sort the highest value. -,-)

Which is bad design.  It would also seem that offline players aren't cached (Or something of the sort) even if their accounts are accessed, because players are crashing the server by buying from offline players.  I think they're both the same.  All the accounts should be cached in memory from boot, and if that's too much to ask (50,000 accounts? That shouldn't take much RAM really... And if it does, cache all accounts as they're seen. offline or online.)

**Comment by ImDeity** [comment]
Any updates on this? Or is iConomy not being maintained any more?

**Comment by Psithief** [comment]
You mean the latest commit?
https://github.com/iConomy/Core/commit/09c86d80cce57b6f327c3f0aadc25fdb051121ca#src/com/iCo6/system/Queried.java

**Comment by surtic86** [comment]
I think iConomy is death. Since two Months no Commit.
