### ISSUE TITLE
'Smart' Partial Name Recognition

### ISSUE THREAD

**Issue by ShafferZee** [iConomy/Core#201]
When using the command '/money <name>' it would be helpful if iConomy had partial name recognition.

ie: '/money fragger505' & '/money fragg' would return the same holdings as long as there isn't an account named fragg or another person named fragg____ within the database. To combat sending money to the wrong account a simple logic function should work.

Exact Name > Partial Name
&&
If no online names match Exact Name or Partial Name, then print listed partial matches and have the user select a numerical match.

ex:
/money pay fragg 1000

=======iConomy=======
No Online Matches - Select Account
1. fragger505
2. fraggfoobar
3. fragglol

/money select 1

Sent $1000 to fragger505's account.

**Comment by netherfoam** [comment]
This should be a requirement for big plugins like this. :/

**Comment by nijikokun** [comment]
Causes issues and we have discussed this in the future. No. Banks don't let you Guess someones name or number. This would be a really bad feature.

**Comment by ShafferZee** [comment]
Not trying to be disrespectful or start up an argument, but the Economy built into Essentials seems the handle partial names really well. However, they do not support bank accounts and other features that iConomy does. iConomy is a much better system over EssentialsEconomy; also it doesn't come with bloat. But is it possible to adopt some methods they use for name recognition?

**Comment by nijikokun** [comment]
I will look into a solution for both parties, and I will look it over with great scrutiny though, it's something that can make or break a society due to mismatching or just bad judgement; I'm not arguing, I'm just thinking about the millions of scenarios and thousands of people using it.
