### ISSUE TITLE
It keeps 'updating' the top.*-messages in Template.yml

### ISSUE THREAD

**Issue by AgentOak** [iConomy/Core#203]
18:18:19 [INFO] [iConomy] Enabling iConomy v7.0
18:18:19 [INFO]  Updating Template Node [top.opening] due to newer variables.
18:18:19 [INFO]  Updating Template Node [top.item] due to newer variables.

It's really annoying, it always replaces my translation of the '/money top'-messages with the default messages.

CraftBukkit 1.2.5-R1.0 Build 2149
iConomy 7.0 April Fools

**Comment by DoubleDeluXe** [comment]
Having the same problem.
I want something like this:

opening: <rose>-----<blue>[ <white>Most Wanted <blue>]<rose>-----

But it changes it back to this:

opening: <green>-----[ <white>Wealthiest Accounts <green>]-----

No matter how small the change, it just resets it.

1.2.5-R4.0 (Build #02222)
iConomy 7.0 April Fools
