### ISSUE TITLE
Database Connection Not Working!

### ISSUE THREAD

**Issue by Phealoon** [iConomy/Core#205]
I have set up the Database, and made sure that the config matches the Database information to the letter, but it still will not connect to the Database. When I load my server, it doesn't even say if the connection was made or not, it is almost as if the config is unaware that there is a Database to connect to. The config does not ask me USEDATABASE: True or any other setting like this. I assumed that it will auto-check for a Database, but it says Nothing. Can I get some help please.

I am using a MySQL Database Workbench.

-Phea

**Comment by RytisRytisRytis** [comment]
MySQL Database Workbench is not a MySQL Database!
