### ISSUE TITLE
Create of accounts does not work

### ISSUE THREAD

**Issue by RamTam** [iConomy/Core#208]
Hi, 
I installed the recommend version of iconomy.
If I try to pay to another account, it says to me that this account does not exist. 
So I created on wit /money create example and it says to me "Created account with the name example.
But If I try now to receive this account with /money pay example or /money status example a message tell me that this account does not exist O_O
In the accounts.mini are no accounts listed even after a /reload
I havn't got this problem earlier, the accounts were all created automatically 
._.'

**Comment by KayzerCode** [comment]
When I type /money status player_name - it replies "Current account status is 0" 
But on /money - it replies "Balance 1000.00"

What is this the account then? Why in status it shows 0 ?
