### ISSUE TITLE
A few bugs that really need to be taken care of!

### ISSUE THREAD

**Issue by Kiwz** [iConomy/Core#214]
First: Flatfile is crap and need to be enhanced or removed.
This is because now and then the holdings is just wiped clear, not cool.

Second: I changed to sqlite to get rid of this problem, and so far so great,
but when I did that none of my players are getting interest (they DO get interest if Online: false).
AND there is no logging of who pays who x amount.

Third: Speaking of interest, the percent interest dosent work, didnt work with flatfile and dont work with sqlite.

Fourth: When interest did work (when I used flatfile) it did not announce to players when they gained interests.

Fith: /money top rly need to get pages and perhaps more than just the top 5 bank account on each page.

Here is my config (just the part of the interest thingy):

Interest:
  Enabled: true
  Online: true
  Announce:
    Enabled: true
  Interval:
    Seconds: 10
  Amount:
    Cutoff: 20000.0
    Percent: 1.0
    Maximum: 10
    Minimum: 5

**Comment by Kiwz** [comment]
Anyone else here who can confirm these bugs?

**Comment by UnknownMage** [comment]
My accounts keep getting reset every once in a while on flatfile.
Moving to MySQL hoping it will stop in the future.

**Comment by RytisRytisRytis** [comment]
This is a known bug:
from the server.log:
[SEVERE] iConomy6 - If you are using Flatfile storage be aware that iCo6 has a CRITICAL bug which can wipe ALL iconomy data.
[SEVERE] if you're using Votifier, or any other plugin which handles economy data in a threaded manner your server is at risk!
[SEVERE] it is highly suggested to use SQL with iCo6 or to use an alternative economy plugin!
