### ISSUE TITLE
Make Server Account

### ISSUE THREAD

**Issue by gabessdsp** [iConomy/Core#220]
So I can't figure out if this is possible or not. I want an account to be created for the server, so I can sell things from a "Server account" or buy things from a "server account". How would I do this if it's already possible? If not, then please add it.

**Comment by Kiwz** [comment]
If you use ChestShop plugin, you can make Admin Shop. An Admin Shop is a shop that has infinite money and if you buy from an Admin Shop it will just delete the money it recieved from you. No need for a server account.
But I think you can create a new account if you like, just dont name it anythin a player would call himself.
/money create name
For complete list of commands type: /money ?
