### ISSUE TITLE
Multiworld iConomy Account

### ISSUE THREAD

**Issue by vpsnak** [iConomy/Core#221]
hello

my name is vpsnak and i am the owner of a server in which we have lot of worlds creative,survival,and other and in there we need multiworld accounts cause we are making a world only for pvp and we should put a shop there cheaper than in our survival map and we want different accounts i read in your bukkit dev page that you have developped multi world accounts but then you wrote version 7 is april fools and i am not sure so can you help me a bit?

ty a lot
vpsnak

**Comment by RytisRytisRytis** [comment]
Not possible at the moment.
