### ISSUE TITLE
Balances randomly going negative

### ISSUE THREAD

**Issue by ghost** [iConomy/Core#222]
Sometimes certain players will randomly lose money from their accounts. At first I thought people were just lying to try to get free money, but then it happened to me as well. I had about 5 million dollars, then I logged in the next day and I had negative 5 million. We don't have anything that allows people to go into negatives (if they can't afford something it will block them from doing it and nobody has perms to take money from other players).

**Comment by Tarquin999** [comment]
Our whole database was wiped clean TWICE, users are randomly losing their money. Is there any answers at all on this MAJOR issue?
