### ISSUE TITLE
Ask for New Feature : account creation / deletion

### ISSUE THREAD

**Issue by tickleman** [iConomy/Core#23]
Would like some kind of :

/money set <playerthathavenoaccountname> <amount>
to create a new account for NPC or player that did never connect to the game

And if possible (but less urgent for me) :
/money newaccount <playerthathavenoaccountname>
/money delaccount <playerwhichiwanttodeleteaccount>
to create/delete account for any existing / non-existing player

Some server admins need it for my RealShop plugin. With it we will be able to give shop to player that have no iConomy bank account yet, and to NPC players !

(for my own server I can do that directly into MySQL, but some folks are not database administrators, and it would be easer for ops to do this in-game)

Thx.

**Comment by nijikokun** [comment]
Added in 4.5.3

**Comment by tickleman** [comment]
Thanks a lot !
