### ISSUE TITLE
MySQL Database Error

### ISSUE THREAD

**Issue by EvanDarwin** [iConomy/Core#24]
I get this following error when trying to start iConomy. I downloaded the MySQL dependency.

16:21:21 [INFO] [iConomy] Failed to connect to database: com.mysql.jdbc.exceptio
ns.jdbc4.MySQLSyntaxErrorException: Unknown database 'minecraft'

**Comment by nijikokun** [comment]
you must create the database, it won't do that for you. It will however create the tables.

**Comment by EvanDarwin** [comment]
OK, I found the error, I didn't put the right database! Thanks!
