### ISSUE TITLE
Update to 1.3.1 RB (#2317)

### ISSUE THREAD

**Issue by Cysioland** [iConomy/Core#242]
Hi. I want to use your plugin on my 1.3.1 server, but there's no version of iConomy for #2317.

**Comment by krisukun** [comment]
Probably noone will update this, this project has become inactive some time ago.
Nijikokun don't have time or abandoned this.
I suggest one thing, switch iconomy to any onther economy plugin, supported by vault.

**Comment by JustOneMoreBlock** [comment]
iConomy 6 Works anyway on 1.3.x - Nothing to fix.

On the other hand CraftConomy is getting widely popular and supported by Vault.
