### ISSUE TITLE
Wont work with shop plugins!

### ISSUE THREAD

**Issue by Fireant456** [iConomy/Core#243]
I use both chestshops and citizens npc trader, when members use them to buy or sell their iconomy accounts don't subtract money or add money.

I suspect that iconomy is not being recognized by other plugins.

PLEASE HELP!
Thanks,
Fireant456

**Comment by krisukun** [comment]
Any errors in console?
On 1.2.5 I didn't have this issues, but on 1.3.1 I didn't tested iConomy.
Maybe it's broken for 1.3.1.
For Citizens You can use reward command: /money give (player) xx (from console), but I don't know why chestshop won't works. Install Vault and try again.
If this still don't working, i suggest to switch to another economy plugin, supported by vault.
