### ISSUE TITLE
Separate Economies For Multiverse

### ISSUE THREAD

**Issue by dmb1107** [iConomy/Core#245]
I have a server with a hardcore raiding map and a skyblock map. Could you make it so I can do split economies for each world in multiverse. Thanks!

**Comment by alien12** [comment]
Definitely something that should be implemented.
It would  be useful for a number of server that run different worlds for different purposes. Such as splitting a pvp world and a build/creative world.

**Comment by BailServe** [comment]
I agree, and hope to see Multiverse compatibility.
