### ISSUE TITLE
An internal error occured while trying to perform this command.

### ISSUE THREAD

**Issue by coltensplat** [iConomy/Core#248]
Whenever I type a command this pops up. The only command that will work is /money help

**Comment by coltensplat** [comment]
nevermind i figured it out

**Comment by worldofneil** [comment]
Any chance you can tell us how you fixed it please? :)

**Comment by worldofneil** [comment]
Solved it too, don't know if same as your way, but we found it wasn't compatible with latest builds of PermissionsEx :(
