### ISSUE TITLE
iConomy Database Disconnect

### ISSUE THREAD

**Issue by averad** [iConomy/Core#25]
Latest iConomy looses connection to database but other plugins do not.

Is MySQL lazy loading enabled in iConomy? (only connecting when a query is being requested)

Note: BigBrother stays 100% connected and never has an issue writing or retrieving data from the same server.

I have monitored the SQL server using MySQL Workbench 5.2 CE and your plugin remains logged into the database. The database overall is transferring at about 13 to 30kb/s , 5 connections to the database, cpu usage is 0%, mem usage is 13% & database key efficiency is 99.82%

There should be 0 latency issues.

Error examples here: http://forums.bukkit.org/threads/econ-iconomy-4-4-7-arcadia-493-531.40/page-59#post-140778

**Comment by nijikokun** [comment]
Try 4.5 and let me know what goes down.
