### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Takedown031** [iConomy/Core#254]
Hello, 

I am thinking of implementing Iconomy onto my server, but have a question:
I already have a custom economy with 3 different tiered currencies (Electronic circuits, biofuel cells, and HV solar arrays, yes I run tekkit) 
And was wondering if I could hook the "money" to those items? For example only use the money to buy those 3 items that they can then use IG (because i don't want a totally EMC-based economy)
Is that possible? Because then they could do jobs etc and then transfer that "virtual" money into the In game "physical" currencies.

Thanks :)

**Comment by Smithey** [comment]
You can't hook directly into iconomy with the items although you could simply run it so they can buy the items in a shop using the iconomy money. You can get plugins like BetterShop for a shop with iconomy support. Sorry if this didn't make sense just let me know if you need any more help.

**Comment by Takedown031** [comment]
That's perfect, just what I wanted to know, thanks a lot ! :)
