### ISSUE TITLE
installation not detailed

### ISSUE THREAD

**Issue by zdoc** [iConomy/Core#26]
ok so i scraped as much as i could from the installation guides but for the life of me i cant seem to figure it out, I have set it up, the money is visible etc etc but when i set up MySQL it started malfunctioning. i tried to edit the money through mysql but i havent a clue how to, mine looked nothing like yours in the video, and i feel it would be easier just to have an in game command system to add, remove, trade, etc money If a more detailed or (for dummies) guide could be released i would be greatful

thank you for your time

**Comment by nijikokun** [comment]
Lamp (linux) or xampp (windows)

PHPMyAdmin

This is as newbie as you can get; It is simple and straight forward. Both of these will setup mysql on your system.

Then modify mysql as needed.
