### ISSUE TITLE
Money loss

### ISSUE THREAD

**Issue by Marathonman123** [iConomy/Core#261]
Every once and a while people will have alot of money then sometimes all the money will get reset and people lose 4/5ths of there money and idk what causes it

**Comment by luijo8989** [comment]
Me too please answer to this issue someone

**Comment by Chaznuts** [comment]
This is a known flat file bug that warns you at the start-up of the server plugins. There is no fix for it if you continue to use the flat file storage. Your only options are to use iConomy storage through another option, like MySQL, or find a different economy plugin.
