### ISSUE TITLE
Online Money Leaderboard

### ISSUE THREAD

**Issue by Longshot555** [iConomy/Core#267]
I think the title sums it up nicely.This plugin needs a way to represent what people make on the server to an online leaderboard, be that for showing off or other various reasons. I hope to see this part of iconomy very soon!

PS. if there is this functionality already, please guide me how to use it!

**Comment by Chaznuts** [comment]
You can use iConomy's MySQL data and have it pulled from a web server where the data can be shown. It's not easy if you don't know what you're doing, but your request is already possible with some work.

**Comment by kroko1992** [comment]
take a look at this ;) http://www.spigotmc.org/resources/iconomy-web.3465/
