### ISSUE TITLE
Create Account Issue

### ISSUE THREAD

**Issue by angiebobb** [iConomy/Core#268]
When I try to add money to a player on my server, it tells me that I have to create an account. So, I try to add an account but I get the message, "An internal error occurred while attempting to perform this command", pops up.

What is happening?

**Comment by Chaznuts** [comment]
If the player is already on your server and it told you to create that account first, you simply misspelled the player's name. Try again, it may be case sensitive ("/money give <player> <amount>"). If the player hasn't been on your server yet, the command to create the account is "/money create <account>"
