### ISSUE TITLE
Please update to 1.8 UUID`s  pretty pls with cherries on top :)

### ISSUE THREAD

**Issue by mcraftpete** [iConomy/Core#273]
I have used this plugin for a long time now and it has worked perfectly always , I have it on 4 of my servers.
I would be sad if it didn't update to uuids , firstly as it ran so well I never had to think about it before and secondly using another plugin means users losing money etc if they change their names.
And again I don't know if another would be as good or as reliable as this.

Please at least a little information ?

Thanks,
Pete

**Comment by FlippantCactus** [comment]
I made a Pull request on this :)
