### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by nijikokun** [iConomy/Core#285]
- [ ] UUID
- [ ] BigDecimal (already have pieces of the code re-written to use them)
- [ ] Remove MiniDB

Anything else?

**Comment by ThePixade** [comment]
Yeahh !!

**Comment by ThePixade** [comment]
For 1.8 ?

**Comment by nijikokun** [comment]
> For 1.8 ?

I hope so! I've been setting up my windows machine environments for this (and bukkit in general).

**Comment by FlippantCactus** [comment]
Welcome back.

**Comment by ghost** [comment]
Hey Nijikokun,
nice to see this. Now 4 month later, do you have any progress or update news to announce? Do you notified the Spigot 1.8 update? http://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-1-8.36598/

Would nice to hear anything! Thanks for iConomy!
