### ISSUE TITLE
[REQ] Please bring back hourly reward / tax

### ISSUE THREAD

**Issue by Snookieboy** [iConomy/Core#3]
I'm migrating from iConomy 2.x and one of the biggest features I'm suprised is missing is the ability to give (or take) a set amount of currency per hour.

On our server, we reward players who play on the server with 2 coins per hour. Besides helping to reward loyalty, it also works to boost the economy and keep it going.

Would you please consider putting this feature back into iConomy?

Many thanks :)

**Comment by nijikokun** [comment]
4.2 contains a feature similiar to this.
