### ISSUE TITLE
Java.lang.NoSuchMethodError: java.io.setwritable(Z)Z Mac

### ISSUE THREAD

**Issue by Tagette** [iConomy/Core#32]
I have gotten this to work without any problems on my PC. I am trying to add the plugin to my mac server. When I run the server it says this error and iConomy doesn't start. It doesn't create an iConomy folder inside the plugins either so it's not because I haven't set any settings. It does create a bin folder in the bukkit server main folder. This bin folder is empty however. I have tried placing the dependencies into the bin as well as in the bukkit server main folder but nothing changed.

This is the full message:

12:11:35 [INFO] Starting minecraft server version Beta 1.3
12:11:35 [INFO] Loading properties
12:11:35 [INFO] Starting Minecraft server on *:25565
12:11:35 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-544-g6c6c30a-b556jnks (MC: 1.3)
12:11:35 [INFO] Preparing level "world"
12:11:35 [INFO] Preparing start region
12:11:36 [INFO] Preparing spawn area: 85%
12:11:37 [INFO] [Permissions] version [2.5.4](Phoenix) was Initialized.
12:11:37 [SEVERE] java.io.File.setWritable(Z)Z loading iConomy v4.5 (Is it up to date?)
java.lang.NoSuchMethodError: java.io.File.setWritable(Z)Z
    at com.nijiko.coelho.iConomy.iConomy.onEnable(iConomy.java:75)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:118)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:451)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:217)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:92)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:70)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:204)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:191)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:131)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:246)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)
12:11:37 [INFO] [Permissions] version [2.5.4](Phoenix)  loaded
12:11:37 [INFO] [PermissionsPlus] plugin version .7b has been enabled.
12:11:37 [INFO] Done (0.131s)! For help, type "help" or "?"

This is quite annoying because all the good plugins for economy require iConomy.

**Comment by nijikokun** [comment]
It's making the lib/ folder writable; make sure you have the correct permissions on files to allow execution; read and write.

**Comment by Tagette** [comment]
I have made everyone have permission to read and write to the entire bukkit folder. Do I have to do the same to every folder inside it? I used getinfo to do this is that correct?

**Comment by Tagette** [comment]
Ok I have made every folder inside the bukkit server folder readable and writable for everyone. However it still has the same problems.

**Comment by Tagette** [comment]
I'm wondering why it says the method doesn't exist...

**Comment by nijikokun** [comment]
Probably a JDK version mismatch. File.setWritable () was added in 1.6.
I am guessing that you are running with an older version.

**Comment by Tagette** [comment]
No i have the most up to date version of java. It is included in system update on a Mac.
