### ISSUE TITLE
Downloading only gives a folder

### ISSUE THREAD

**Issue by Joself** [iConomy/Core#34]
As the title says, when downloading the .jar, I only get a folder named iConomy. I tried to rename it, but with no succes. If it matters, I'm on a Mac.

**Comment by Tagette** [comment]
Its because the extractor your using also expands the '.jar' that is inside the '.zip'.
Use another extracter. Instead of double clicking the .zip file, right click it and Open With something that isn't the default. If you don't have another extracter try 'Stuffit Expander'. Search it in google.

**Comment by Joself** [comment]
Thank you so much! Finnaly, I can use the plugins I really want!

**Comment by Tagette** [comment]
Your welcome, I'm not so lucky though =l. My server still has a silly error with iConomy.

**Comment by Joself** [comment]
Neither am I, the balances aren't updating... :S
