### ISSUE TITLE
New user group has no account [new feature]

### ISSUE THREAD

**Issue by saladin1980** [iConomy/Core#35]
Ok basically how i setup the server is they have to request access to build or do anything... now with this i would like that they are not even setup as a user until i get them in the builders group now with that just somthing that i would like to have if not already in the system.

**Comment by nijikokun** [comment]
It gives everyone access to /money and /money? someone else requested something like this (if it was you im sorry) but, I'm probably just going to add permissions for /money and /money ? that way you can prevent them from using it.

**Comment by saladin1980** [comment]
yea basically that is the thing so they are not allowed access to there money until i am able to give them access bc right now even though they cant build they can stil buy item that would undermine the whole thing:)  and i think itwas me that was the one that did the request on the forums only found this so i thought this would be the best way to make the request;)   but ya if there was a way to deny them use of the money at all that would be great
