### ISSUE TITLE
IConomy is not updating balances

### ISSUE THREAD

**Issue by DanJames** [iConomy/Core#37]
Hello,

I'm running the latest build of IConomy, but it doesn't seem to be updating balances. I'm running loads of plugins, the ones that use IConomy are:

LocalShops
BankAccounts

If someone can help me with this issue it would be great.

DanJames

**Comment by Joself** [comment]
Same thing happes to me. I'm using Turnstile, BankAccounts (that doesn't work) and Lottery. Turnstiles and Lottery says that they've charged me, but I still got 100 of my currency. Paying, giving myself extra money, winning money in the Lottery and so on doesn't help, I'm still stuck at 100...

**Comment by nijikokun** [comment]
Fixed in 4.6.1+
