### ISSUE TITLE
Command not working properly

### ISSUE THREAD

**Issue by Lolmewn** [iConomy/Core#39]
I get this error, with a new generated iConomy folder (so it's not my settings that are messing):
12:29:31 [SEVERE] java.lang.IllegalArgumentException: Malformed pattern "#.##0,##"
12:29:31 [SEVERE]       at java.text.DecimalFormat.applyPattern(Unknown Source)
12:29:31 [SEVERE]       at java.text.DecimalFormat.<init>(Unknown Source)
12:29:31 [SEVERE]       at com.nijiko.coelho.iConomy.system.Account.toString(Account.java:142)
12:29:31 [SEVERE]       at com.nijiko.coelho.iConomy.system.Bank.format(Bank.java:72)
12:29:31 [SEVERE]       at com.nijiko.coelho.iConomy.entity.Players.showBalance(Players.java:118)
12:29:31 [SEVERE]       at com.nijiko.coelho.iConomy.entity.Players.onPlayerCommand(Players.java:442)
12:29:31 [SEVERE]       at com.nijiko.coelho.iConomy.iConomy.onCommand(iConomy.java:210)
12:29:31 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)
12:29:31 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:80)
12:29:31 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:229)
12:29:31 [SEVERE]       at net.minecraft.server.NetServerHandler.c(NetServerHandler.java:645)
12:29:31 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:608)
12:29:31 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:602)
12:29:31 [SEVERE]       at net.minecraft.server.Packet3Chat.a(SourceFile:24)
12:29:31 [SEVERE]       at net.minecraft.server.NetworkManager.a(SourceFile:230)
12:29:31 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:76)
12:29:31 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile:100)
12:29:31 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:357)
12:29:31 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:272)
12:29:31 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)

**Comment by nijikokun** [comment]
Fixed in 4.6.1+

**Comment by Lolmewn** [comment]
Great!
