### ISSUE TITLE
Half working?

### ISSUE THREAD

**Issue by Darkestofdays** [iConomy/Core#41]
my iconomy seems to be... well somekinda working. the only command that works is /money help. not even /money works

please reply on this problem, propperly me!

**Comment by saladin1980** [comment]
have u setup permissions or groupmager or anything of the sorts and if so make sure that the right permissions are setup and if not then i am not sure they will have to help ya . but i would dbl check the permissions and if u have OP on the server .. op shouldn't be required but a good test to make sure... and that would be the only way that i know of to get permissions to use the commands.. also is the database setup and such properly?

**Comment by nijikokun** [comment]
You are probably having database issues, or something. It fully works here. I don't release it if it doesnt.
