### ISSUE TITLE
[REQ] Clear Unused accounts

### ISSUE THREAD

**Issue by mr-bo-jangles** [iConomy/Core#43]
/money clean   - removes accounts from DB with default value
/money hnb     - Gives user hookers and blow at cost of health

**Comment by nijikokun** [comment]
The first one will be added, but the seconds one no :P

Also, should it be for banks & holdings, or should /money clean just do holdings and /bank clean do banks

**Comment by mr-bo-jangles** [comment]
it is for maintainance, so i assume both? it's to keep the number of records down
