### ISSUE TITLE
Commands rank and top do not work

### ISSUE THREAD

**Issue by timosong** [iConomy/Core#44]
I'm using craftbukkit 556 and iConomoy v4.6.3
/money rank and /money top do not work for admins or users given access to that command.
When i use /money rank I get an output:
[Money] Current rank: -1

and /money top:
[Money] Top 0 Richest Players:

Also, not sure if this is the right place to ask, but am I required to make a separate database like shown in the tutorial videos? (i.e. making a mysql database at db4free)

**Comment by LordCrazyKing** [comment]
I'm also getting this problem, it worked fine before the recent update (last one or 2 versions).

**Comment by nijikokun** [comment]
Happens if your database cannot respond in adequate time or you used an invalid version.

**Comment by puretalent** [comment]
What if i have no database
