### ISSUE TITLE
using /money top with 4.6.5

### ISSUE THREAD

**Issue by bigougit** [iConomy/Core#48]
when using /money top with iConomy 4.6.5 and CB617 i get this error

04:54:20 [SEVERE] org.h2.jdbc.JdbcSQLException: Column "HIDDEN" not found; SQL s
tatement:
SELECT \* FROM iConomy WHERE hidden = 0 ORDER BY balance DESC LIMIT 5 [42122-153]

04:54:20 [SEVERE]       at org.h2.message.DbException.getJdbcSQLException(DbExce
ption.java:327)
04:54:20 [SEVERE]       at org.h2.message.DbException.get(DbException.java:167)
04:54:20 [SEVERE]       at org.h2.message.DbException.get(DbException.java:144)
04:54:20 [SEVERE]       at org.h2.expression.ExpressionColumn.optimize(Expressio
nColumn.java:134)
04:54:20 [SEVERE]       at org.h2.expression.Comparison.optimize(Comparison.java
:154)
04:54:20 [SEVERE]       at org.h2.command.dml.Select.prepare(Select.java:794)
04:54:20 [SEVERE]       at org.h2.command.Parser.prepare(Parser.java:202)
04:54:20 [SEVERE]       at org.h2.command.Parser.prepareCommand(Parser.java:214)

04:54:20 [SEVERE]       at org.h2.engine.Session.prepareLocal(Session.java:426)
04:54:20 [SEVERE]       at org.h2.engine.Session.prepareCommand(Session.java:374
)
04:54:20 [SEVERE]       at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnect
ion.java:1100)
04:54:20 [SEVERE]       at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPrepared
Statement.java:71)
04:54:20 [SEVERE]       at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConne
ction.java:243)
04:54:20 [SEVERE]       at com.nijiko.coelho.iConomy.system.Bank.getAccountRanks
(Bank.java:230)
04:54:20 [SEVERE]       at com.nijiko.coelho.iConomy.entity.Players.showTop(Play
ers.java:393)
04:54:20 [SEVERE]       at com.nijiko.coelho.iConomy.entity.Players.onPlayerComm
and(Players.java:474)
04:54:20 [SEVERE]       at com.nijiko.coelho.iConomy.iConomy.onCommand(iConomy.j
ava:216)
04:54:20 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:35)
04:54:20 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:80)
04:54:20 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(Cr
aftServer.java:233)
04:54:20 [SEVERE]       at net.minecraft.server.NetServerHandler.c(NetServerHand
ler.java:594)
04:54:20 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerH
andler.java:557)
04:54:20 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:551)
04:54:20 [SEVERE]       at net.minecraft.server.Packet3Chat.a(SourceFile:24)
04:54:20 [SEVERE]       at net.minecraft.server.NetworkManager.a(NetworkManager.
java:198)
04:54:20 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:72)
04:54:20 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile
:100)
04:54:20 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServe
r.java:368)
04:54:20 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:283)
04:54:20 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(Sour
ceFile:375)

**Comment by puretalent** [comment]
Same for me.

**Comment by nijikokun** [comment]
Re-download 4.5.6; Delete database; Restart.
