### ISSUE TITLE
[REQ] Interest / Account cutoff amount

### ISSUE THREAD

**Issue by SamuraiSkye** [iConomy/Core#49]
There should be a way to set an account amount that the interest will stop at.  For example an account starts with zero credits, then as the interest gives them money, it stops giving them money when they are at or higher then 100 credits.

This could be implemented in two ways, either a master account max money variable in the settings file, or an interest cap variable at which it stops giving interest.  Or both, since i can see both the interest and master account max being useful in certain cases.

**Comment by nijikokun** [comment]
I will see what can be done in 5.0
