### ISSUE TITLE
[REQ] Separate balances for each world

### ISSUE THREAD

**Issue by spathizilla** [iConomy/Core#51]
Just a feature request:

Have a configuration option to allow the balance on different worlds to be kept separately - also allow world pairing to share the balance for that world (ie they act as one world for iConomy).

This would allow me to have a shared balance with the mainworld and nether but keep a separate balance for the survival world. I'd love to have an economy in the survival world but I dont want it being influenced by the other worlds.

**Comment by nijikokun** [comment]
Actually, this might be postponed for future releases.

**Comment by Enf0** [comment]
Looking foward to seeing this implemented.

**Comment by duxet** [comment]
It would be really useful. I have two worlds, and can't use money at the second one.

**Comment by ghost** [comment]
any update on the implementation?
