### ISSUE TITLE
Time out issue?

### ISSUE THREAD

**Issue by ItalianGuy21** [iConomy/Core#54]
Since i got iconomy, i have problems logging into my server every time i log into my server it either times me out or it just freezes but then again when i delete my iconomy plugin folder and .jar it works fine this is really annoying and i cant figure it out please help.

**Comment by nijikokun** [comment]
iConomy does not cause extra loads on servers unless you are using a remote database.

**Comment by ItalianGuy21** [comment]
But then how could i not use a remote database like mySQL
