### ISSUE TITLE
[REQ] Local transactions.

### ISSUE THREAD

**Issue by Peaced** [iConomy/Core#59]
Player can only do transaction to other closeby players.

**Comment by nijikokun** [comment]
Radius based?

**Comment by Mineral** [comment]
I like this, particularly coupled with the new banking system. Will be a nice touch for RP servers. Face to face, radius in option - default 6 blocks?

**Comment by Peaced** [comment]
Yes radius based. (or square most proabably :)*
Configurable may be ? else 10 blocks seems a fair distance.

**Comment by nijikokun** [comment]
It will be configurable / toggable.

10 Will be the default
