### ISSUE TITLE
[REQ] Multiple Currencies

### ISSUE THREAD

**Issue by lhwrd** [iConomy/Core#60]
I'm starting up a new RP server called LifeRP, based solely upon the principals of real life. Since my map is going to be fricken huge (The Earth map), I'm proposing multiple currencies. Maybe a limit of up to 5 or something? And a fluctuation of the value of each currency. And depending on the spawn location, the default currency to be set to that spawn location.

**Comment by nijikokun** [comment]
Each bank will support alternative currencies, so this will be in 5.0
