### ISSUE TITLE
4.6.5 Fail to recognize names?

### ISSUE THREAD

**Issue by illuminath** [iConomy/Core#61]
i have installed everything correctly, i get no errors on the console but when i try to do commands in game the only command i can get working is /balance Player or /money player

 the rest of the commands give me an error
" Error: no matching players could be found " 

i have tried doing the commands many ways but still cant get it to work, any help is appreciated

**Comment by nijikokun** [comment]
Has to be exact to prevent you from accidentally doing something on the wrong person. Yes, matching is nice, but money is a sensitive subject.
