### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Ahfaichucky** [iConomy/Core#64]
I'm having a issue where my console is spammed with this, sometimes it just goes on for like 15 mins, and cause my cpu usage to go up..I'm using RB 740 and iconomy 4.6.5 using mysql.

Money:0
Money:0
Money:1000
Money:0
Money:0
Money:0

**Comment by nijikokun** [comment]
Check to see if you have Interest on, or if a user is continuously spamming the /money command :P

**Comment by Ahfaichucky** [comment]
i dont have interest on, it happens randomly though, is there a way to not output it to console if its related to /money command spam

**Comment by nijikokun** [comment]
Check with ico5
