### ISSUE TITLE
Multi-User Accounts

### ISSUE THREAD

**Issue by PrivateAlpha** [iConomy/Core#68]
Simple, Allow more than one user to be linked to one account, this would be great for shared accounts

**Comment by nijikokun** [comment]
Ideas on how this could be integrated with the current system, as I don't see a way at the moment.

**Comment by PrivateAlpha** [comment]
I'm still playing with iConomy(learning howto use it),i'm sure once i have learnt a bit more i'll be able to think out a few ideas.

**Comment by Ret311** [comment]
I too would like to see shared bank accounts in the near future. I know there is another plugin developer that maybe you can contact for help on this issue. His/her name is TAT on the bukkit forums, and the plugin they made is here:

http://forums.bukkit.org/threads/econ-bankaccount-v-0-5-shared-bank-accounts-using-iconomy-4-x-740.7095/

Just an idea. I really hope to see this!!

**Comment by Enf0** [comment]
Any update on this?

**Comment by nijikokun** [comment]
Banks are being removed, TAT's will probably be the main system for banks
