### ISSUE TITLE
Commands won't work even though '*' and no user specified permissions

### ISSUE THREAD

**Issue by Adrian16** [iConomy/Core#69]
Yeah I installed Iconomy and used MySQL.

1.I changed the config to my likes and restarted the server.
2.I tried /money and it showed me my money working correctly
3.I tried /bank create "myname" and nothing happened
4.I Went to my server console and typed the same command again and it said the bank account was created and as i looked into my Db's it was also in there 

I tried to type /bank again and it still said : No Bank accounts were found on this account.

The point is: The plugin gets Db connection and i can create accounts with the server console, but the banks won't work ingame and i can't use commands(just nothing happens)
Im Ops and my permissions plugin works fine for every plugin i have installed. (im using phoenix permission)
I dont get any errors when i try to use a command (not ingame and not in the server console)
The only commands that work are : /bank (telling me there are no accounts)
                                                                /bank ? telling me the commands : /bank and  /bank ?
                                                                /money telling me my money ammount (working fine)
                                                                / money ? telling me there are these commands: /money ? and /money

As I said my permissions plugin is configured right because it works for every other plugin AND I am Ops
I cant find out what im making wrong so it has to be a bug.
I am using 5.0

I hope anyone can help me...

**Comment by nijikokun** [comment]
if you are inheriting anyone or if you have permissions on your person, you override the '*' thus making your permissions moot. it doesn't matter if you are OP or not. If your permissions are messed up then you won't be able to use it.

Don't blame iConomy for incorrectly setting up Permissions.

**Comment by Adrian16** [comment]
I wasnt sure about it so i asked anyways i reinstalled permissions and that fixed the problem, I also didnt set any inheriting or other permissions to the user and the admin group, apearently, permissions just broke
