### ISSUE TITLE
Getting to the bottom of why this plugin has issues with Chat Mods

### ISSUE THREAD

**Issue by Snookieboy** [iConomy/Core#7]
Many servers use mods like iChat or Herochat. These have never had problems before with other mods that take commands via the chat. 

For some reason, with these mods running only the /money command works, even when permissions are set perfectly.

Due to the sheer number of mods which work along side these plugins (Including the old iConomy 2.x and 3.x) when issuing commands via in-game chat it has to be an issue related to iConomy 4.x I'm afraid. Can this please be looked into?

Please :)

**Comment by nijikokun** [comment]
It is, and still unknown. Probably the permissions issue, it's being fixed.
