### ISSUE TITLE
Bank Interest not working

### ISSUE THREAD

**Issue by NeatMonster** [iConomy/Core#72]
Hello, (Excuse-me for my bad English, I'm French.)

I've set the interest on 'Banks' on the configuration file, but they are reversed to ALL the players. Is this broken?

I would like to see this errors solved.

Thanks in advance, NeatMonster.

**Comment by NeatMonster** [comment]
Help please ?

**Comment by nijikokun** [comment]
It should create accounts, it might be a database issue; Backup your old database, and move it to a sub directory; and try with a new database.

Also lack of information such as what database type you are using and etc.

**Comment by NeatMonster** [comment]
First issue solve. Second issue is already here.

**Comment by nijikokun** [comment]
The banks or accounts?

**Comment by NeatMonster** [comment]
I set the setting to Banks, but money reverses on the accounts of every player instead of their bank account.

**Comment by NeatMonster** [comment]
I was talking about interests.

**Comment by nijikokun** [comment]
Updated

**Comment by NeatMonster** [comment]
?

**Comment by NeatMonster** [comment]
Any update?

**Comment by NeatMonster** [comment]
Are you here?

**Comment by MSylvia** [comment]
Confirming I have the issue as well on iConomy 5.0 (Eruanna).
