### ISSUE TITLE
Icoland Problem

### ISSUE THREAD

**Issue by NeoBLu** [iConomy/Core#73]
Hi there
I´ve got a Problem with iColand, seems to be not compatible with iConomy 5 yet.
Didn´t knew how to contact because it still don´t work and i´ve got some Plugins who need iConomy 5.

**Comment by nijikokun** [comment]
Wrong plugin to open issue on, https://github.com/iConomy/iCoLand/issues

**Comment by magik** [comment]
this should already be fixed - have you tried using the latest iCoLand? v 2.64

http://forums.bukkit.org/threads/sec-econ-icoland-v2-46-buy-protect-land-with-iconomy-740.9978/

**Comment by NeoBLu** [comment]
Hey you´re right!Thx a lot, was checking for updates more than twice on ur site!
Works Perfectly, i tested out already
