### ISSUE TITLE
Banks not working + Internal Errors + Interest does not use Minor Currency

### ISSUE THREAD

**Issue by Xaymar** [iConomy/Core#79]
[b]Craftbukkit Version:[/b] b729
[b]iConomy version:[/b] 5.0.?
[b]Current Issue / Error:[/b] Internal Error
[b]Console Output w/ Full Error[/b](Preferably using http://pastie.org or http://pastebin.com):
http://pastebin.com/T5nJCrJq
[i]What you were doing?[/i]
/money stats
[i]Were you upgrading?[/i]
No
[i]Is this a reoccuring issue?[/i]
Always happens

Also how do Banks work? I've set Interest->On to "Banks" and players still don't recieve the interest onto their bank. How do they deposit/withdraw money?

Also an option to enable Minor Interest would be nice, currently it's being rounded, which ends up in players below 50 Major Currency getting nothing(1% Interest).

**Comment by nijikokun** [comment]
Banking must be set to true.

**Comment by Xaymar** [comment]
It is. Figured out how to withdraw and deposit money myself, because it's not covered anywhere.
Any ETA on the interest fix?

**Comment by MercAB3** [comment]
I made a fork to try and fix the Minor Interest issue. Could either of you check it out to make sure I did it right?
