### ISSUE TITLE
Dynamic function

### ISSUE THREAD

**Issue by Linaks** [iConomy/Core#8]
Please turn the dynamic-function on!
I have to type /reload for reloading the database.
So if I change anyones' money in MySQL Database, i have to type /reload.
Earlier it reloaded itself. Please make it dynamic again ;)

**Comment by jascotty2** [comment]
i'd also like this.. then i could update user accounts from my website

**Comment by nijikokun** [comment]
It's been updated in 4.4

**Comment by Linaks** [comment]
Thanks but i tried with SQLite and MySQL it doesn't work
I changed the iBalances table with another value but only if i type /reload it works :(

**Comment by nijikokun** [comment]
4.4.3 added this.

**Comment by Linaks** [comment]
So now I can edit my MySQL table and if I save it it's also inGame?
I Have 4.4.4 but i doesn't work :( Please try it on your own

**Comment by jascotty2** [comment]
there's a new field under Database:
        # Should balances be cached and saved when requested (true)

```
    # Or do you wish for it to be constantly grabbing the balance

    # from the database (false)

    Cache: true
```

set to false to have the plugin get the values for the database each time

**Comment by Linaks** [comment]
Oh thanks <3
