### ISSUE TITLE
[BUG][5.0.1] /bank remove non-functional

### ISSUE THREAD

**Issue by SquallSeeD31** [iConomy/Core#82]
[b]Craftbukkit Version:[/b] b766
[b]iConomy version:[/b] 5.0.1

[b]Current Issue / Error:[/b] "/bank remove" command is nonfunctional; produces no output and does not effect removal of bank.  No reference is made in code to any method that would remove a bank.

[b]Console Output w/ Full Error[/b](Preferably using http://pastie.org or http://pastebin.com): As stated, no output.

[i]What you were doing?[/i] Typing command /bank remove TestBank

[i]Were you upgrading?[/i] Yes, from 4.X

[i]Is this a reoccuring issue?[/i] Yes, reproducible 100%

**Comment by jigsawspain** [comment]
I'm having the exact same issue...
I also cannot create an account using /bank join Bank
