### ISSUE TITLE
not using iconomy

### ISSUE THREAD

**Issue by codysrk** [iConomy/Core#87]
i have the next plugins : -Permissions
-Essentials
-Iconomy
-Citizens
and when i try to put a prince on my trader at citizen with iconomy it says : Iconomy is not on this server or something like that , please help ? >_<

**Comment by Sleaker** [comment]
Essentials has it's own builtin economy, trying to load both has a tendency to cause issues. Most likely you need to disable Essentials or Essential's Economy functions.
