### ISSUE TITLE
Adding support of real items for money

### ISSUE THREAD

**Issue by Sphax84** [iConomy/Core#89]
Please, would it be possible to support one or more items as money instead of virtual $$$ ?

For example, I would like players to buy/sell with diamonds (=100$), gold ingots (=50$), iron ingots (=10$) and cookies (=1$). 

Players will need to have those items in their inventory to be able to buy anything. And if a player sell something, he will get the money as items directly in its inventory in the simplest solution.

For example:
- Player X buy an item which costs 23$. He needs to have 23 cookies or 2 iron ingots + 3 cookies. The items will be deleted from its inventory if the transaction is validated.
- Player X sell an item which costs 62$. He will get 1 gold ingot, 1 iron ingot and 2 cookies.

An options for selling would be to automatically get the payment in a specific chest with a sign to identify it... (Think of the thefts in the world, that would be awesome :p ).

To simplify this idea it could be possible to define only one item for 1$. :)

**Comment by nijikokun** [comment]
Hm, yes I want to support this method, I will write up a layer for it as a 'database' ;)
