### ISSUE TITLE
More bank functionality

### ISSUE THREAD

**Issue by LordCrazyKing** [iConomy/Core#98]
At the moment it seems like having multiple banks is a waste of time, unless i'm missing something the only difference is the name and the join cost, and as they can be accessed from anywhere then surely everyone will just join the cheapest one.

My suggestions for banks:
- Make them location based, i.e. you must be within a radius of a selected point (or within a cubioid region) to use the bank commands (other than things like list which can be global, each bank will have it's own area).
- Add bank owners, have each bank linked to a player's account (or a main account in that bank for a player) which all the join fees go to (and maybe even where interest is taken from) also have the bank owner be able to access all accounts within that bank. Maybe use a system where there's only X real currency in the bank 'vault' but the players accounts list how much they should have and only when they deposit/withdraw money does the banks money stash change (this part might be a taking it a bit far).
- Allow each bank to set its own interest rate.
- Shared accounts, account owners who can deposit and withdraw, account users that can only deposit.
- Also a bank grant/take command for admins would be nice.

**Comment by EMOberger** [comment]
"- Allow each bank to set its own interest rate"

yay I'm not the only one who thinks so -.-
